const KEY='copero2-save';
const $=s=>document.querySelector(s);
const money=n=>`€${Math.round(n).toLocaleString()}`;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const pick=a=>a[Math.floor(Math.random()*a.length)];

const clubNames=['Northbridge FC','Riverside United','Kingsport City','Eastvale Athletic','Redmont FC','Harbor Rovers','Westford Town','Stonebridge','Valencia Norte','Lakeside FC','Crown Athletic','Metro Albion','Oakchester','Southbank FC','Greenwich Rovers','Ironvale'];
const first=['Alex','Luca','Noah','Ethan','Mateo','Leo','Milo','Daniel','Theo','Oscar','Jamie','Nico','Ryan','Kai','Adam','Eli'];
const last=['Carter','Moretti','Bennett','Silva','Morgan','Hayes','Turner','Rossi','Walker','Young','Cooper','Miller','Parker','Reed','Costa','Foster'];
const positions=['GK','LB','CB','RB','CDM','CM','CAM','LW','RW','ST'];

function makePlayer(i,clubId){
  const age=rand(17,34), ovr=rand(58,82), potential=clamp(ovr+rand(3,18)-(age>25?rand(0,8):0),ovr,90);
  return {id:`p${i}`,name:`${pick(first)} ${pick(last)}`,age,position:pick(positions),ovr,potential,clubId,wage:rand(3,35)*1000,contractYears:rand(1,5),value:Math.round(ovr*ovr*900),morale:rand(65,90),form:rand(60,85),apps:0,goals:0,assists:0,internationalCaps:0,internationalGoals:0};
}
function seed(){
 const clubs=clubNames.map((name,i)=>({id:`c${i}`,name,division:i<8?1:2,budget:25_000_000-i*700_000,wageBudget:300_000-i*5_000,reputation:60+Math.max(0,20-i),points:0,wins:0,draws:0,losses:0,gf:0,ga:0}));
 const players=[]; for(let i=0;i<240;i++) players.push(makePlayer(i,clubs[i%clubs.length].id));
 return {year:2030,month:7,day:1,clubs,players,user:null,fixtures:[],news:['COPERO II begins. It is not Copero.','Pre-season has started. Humanity remains obsessed with football.'],offers:[],career:[],page:'dashboard'};
}
let state=load()||seed();
function load(){try{return JSON.parse(localStorage.getItem(KEY))}catch{return null}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function club(){return state.clubs.find(c=>c.id===state.user.clubId)}
function user(){return state.players.find(p=>p.id===state.user.playerId)}
function daysToNextMatch(){return 7-(state.day%7);}
function overall(p){return p.ovr}

function render(){
 if(!state.user)return renderStart();
 const nav=['dashboard','player','matches','league','contracts','transfers','career'];
 $('#app').innerHTML=`<div class="app"><header class="top"><div class="brand">COPERO II: NOT COPERO</div><div class="sub">PLAYER CAREER SIMULATION · ${state.year}/${String(state.year+1).slice(2)}</div></header><div class="layout"><nav class="nav">${nav.map(n=>`<button class="${state.page===n?'active':''}" data-page="${n}">${label(n)}</button>`).join('')}<button data-action="save">💾 Save</button><button data-action="new">↻ New Career</button></nav><main class="main">${page()}</main></div></div>`;
 bind();
}
function label(n){return {dashboard:'Dashboard',player:'My Player',matches:'Matches',league:'League Table',contracts:'Contracts',transfers:'Transfers',career:'Career History'}[n]||n}
function renderStart(){
 $('#app').innerHTML=`<div class="start"><div class="startbox"><div class="eyebrow">COPERO II</div><h1>NOT COPERO</h1><p>A football career simulator where contracts actually matter and seasons actually advance.</p><form id="create" class="form"><label>Name<input name="name" value="Alex Carter" required></label><label>Position<select name="position">${positions.map(p=>`<option>${p}</option>`).join('')}</select></label><label>Nationality<input name="nation" value="England" required></label><button class="btn">Start Career</button></form><div class="muted small">Your first contract, transfer market and entire career are simulated from here.</div></div></div>`;
 $('#create').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);createCareer(f.get('name'),f.get('position'),f.get('nation'));};
}
function createCareer(name,pos,nation){
 state=seed(); const starter=state.clubs.find(c=>c.division===2); const p={id:'user',name,age:18,position:pos,ovr:64,potential:84,clubId:starter.id,wage:7000,contractYears:3,value:4_500_000,morale:78,form:70,apps:0,goals:0,assists:0,internationalCaps:0,internationalGoals:0,nation}; state.players.push(p); state.user={playerId:'user',clubId:starter.id}; state.news.unshift(`${name} signs a 3-year contract with ${starter.name}.`); save(); render();}

function page(){switch(state.page){case'player':return playerPage();case'matches':return matchesPage();case'league':return leaguePage();case'contracts':return contractsPage();case'transfers':return transfersPage();case'career':return careerPage();default:return dashboard();}}
function dashboard(){const p=user(),c=club(),next=nextFixture();return `<div class="pagehead"><div><div class="eyebrow">${state.year}/${String(state.year+1).slice(2)}</div><h1>${p.name}</h1><div class="muted">${p.position} · ${c.name} · ${p.age} years old</div></div><button class="btn" data-action="advance">Advance ${daysToNextMatch()} days</button></div><div class="grid"><section class="card hero"><div class="row"><div><div class="muted">Overall</div><div class="big">${p.ovr}</div></div><span class="pill">Potential ${p.potential}</span></div><div class="stat">Form <b>${p.form}/100</b></div><div class="stat">Morale <b>${p.morale}/100</b></div><div class="stat">Contract <b>${p.contractYears.toFixed(1)} yrs</b></div><div class="stat">Wage <b>${money(p.wage)}/week</b></div></section><section class="card"><div class="muted">NEXT MATCH</div><h2>${next?next.opponent:'Season break'}</h2><p>${next?'League · '+next.date:'Advance the calendar'}</p></section><section class="card"><div class="muted">CLUB</div><h2>${c.name}</h2><p>Division ${c.division}</p><p>League position: ${positionOf(c.id)}</p></section><section class="card"><div class="muted">CAREER</div><h2>${p.apps} apps</h2><p>${p.goals} goals · ${p.assists} assists</p></section><section class="card"><div class="muted">RECENT NEWS</div>${state.news.slice(0,4).map(n=>`<div class="notice">${n}</div>`).join('')}</section></div>`}
function playerPage(){const p=user(),c=club();return `<div class="pagehead"><div><div class="eyebrow">MY PLAYER</div><h1>${p.name}</h1><div class="muted">${p.nation} · ${p.position} · ${c.name}</div></div></div><div class="grid"><section class="card"><h2>Profile</h2>${stat('Overall',p.ovr)}${stat('Potential',p.potential)}${stat('Age',p.age)}${stat('Value',money(p.value))}${stat('Wage',money(p.wage)+'/week')}</section><section class="card"><h2>Development</h2>${stat('Form',p.form+'/100')}${stat('Morale',p.morale+'/100')}<p class="muted">Development is affected by age, performances, playing time and potential.</p></section><section class="card"><h2>Career totals</h2>${stat('Appearances',p.apps)}${stat('Goals',p.goals)}${stat('Assists',p.assists)}${stat('International caps',p.internationalCaps)}${stat('International goals',p.internationalGoals)}</section></div>`}
function stat(a,b){return `<div class="stat">${a}<b>${b}</b></div>`}
function matchesPage(){const rows=state.fixtures.filter(f=>f.clubId===club().id).slice(-8).reverse();return `<div class="pagehead"><div><div class="eyebrow">FIXTURES</div><h1>Matches</h1></div><button class="btn" data-action="advance">Advance ${daysToNextMatch()} days</button></div><section class="card"><table class="table"><thead><tr><th>Date</th><th>Opponent</th><th>Result</th><th>Rating</th></tr></thead><tbody>${rows.map(f=>`<tr><td>${f.date}</td><td>${f.home?f.opponent:'@ '+f.opponent}</td><td>${f.result||'Upcoming'}</td><td>${f.rating||'—'}</td></tr>`).join('')}</tbody></table></section>`}
function leaguePage(){const div=club().division;const list=state.clubs.filter(c=>c.division===div).sort((a,b)=>b.points-a.points||((b.gf-b.ga)-(a.gf-a.ga)));return `<div class="pagehead"><div><div class="eyebrow">DIVISION ${div}</div><h1>League Table</h1></div></div><section class="card"><table class="table"><thead><tr><th>#</th><th>Club</th><th>Pts</th><th>W</th><th>D</th><th>L</th><th>GD</th></tr></thead><tbody>${list.map((c,i)=>`<tr class="${c.id===club().id?'highlight':''}"><td>${i+1}</td><td>${c.name}</td><td>${c.points}</td><td>${c.wins}</td><td>${c.draws}</td><td>${c.losses}</td><td>${c.gf-c.ga}</td></tr>`).join('')}</tbody></table></section>`}
function contractsPage(){const p=user(),months=p.contractYears*12;return `<div class="pagehead"><div><div class="eyebrow">CONTRACT</div><h1>${club().name}</h1></div></div><section class="card"><div class="row"><div><h2>${p.name}</h2><div class="muted">${months.toFixed(1)} months remaining</div></div><span class="pill">${p.contractYears.toFixed(1)} years</span></div>${stat('Weekly wage',money(p.wage))}${stat('Estimated value',money(p.value))}${stat('Squad role','Rotation')}<div class="actions"><button class="btn" data-action="negotiate">Negotiate Extension</button><button class="btn secondary" data-action="request">Request Transfer</button></div></section>`}
function transfersPage(){const p=user();if(!state.offers.length)return `<div class="pagehead"><div><div class="eyebrow">MARKET</div><h1>Transfers</h1></div></div><section class="card"><p>No active offers.</p><p class="muted">Offers can appear after strong performances, especially when your contract is getting shorter.</p></section>`;return `<div class="pagehead"><div><div class="eyebrow">MARKET</div><h1>Transfer Offers</h1></div></div>${state.offers.map((o,i)=>`<section class="card offer"><div class="row"><div><h2>${o.clubName}</h2><div class="muted">${o.role} · ${o.years} years</div></div><strong>${money(o.wage)}/week</strong></div><p>Transfer fee: ${money(o.fee)} · Release clause: ${money(o.release)}</p><div class="actions"><button class="btn" data-offer="${i}" data-choice="accept">Accept</button><button class="btn secondary" data-offer="${i}" data-choice="reject">Reject</button></div></section>`).join('')}`}
function careerPage(){const p=user();return `<div class="pagehead"><div><div class="eyebrow">HISTORY</div><h1>Career History</h1></div></div><div class="grid"><section class="card"><h2>Career</h2>${state.career.length?state.career.map(x=>`<div class="notice"><b>${x.season}</b><br>${x.club} · ${x.apps} apps · ${x.goals} goals</div>`).join(''):'Your career history will appear after your first completed season.'}</section><section class="card"><h2>Honours</h2><p class="muted">${state.career.filter(x=>x.trophy).map(x=>x.trophy).join('<br>')||'No trophies yet.'}</p></section></div>`}
function nextFixture(){return state.fixtures.find(f=>f.clubId===club().id&&!f.result)}
function positionOf(id){const div=state.clubs.find(c=>c.id===id).division;return state.clubs.filter(c=>c.division===div).sort((a,b)=>b.points-a.points||((b.gf-b.ga)-(a.gf-a.ga))).findIndex(c=>c.id===id)+1}

function advance(){
 const p=user(),c=club(); state.day+=daysToNextMatch(); if(state.day>28){state.day=1;state.month++;}
 if(state.month>6){finishSeason();state.month=7;state.day=1;}
 const f=nextFixture(); if(f) playMatch(f);
 p.contractYears=Math.max(0,p.contractYears-1/12);
 p.form=clamp(p.form+rand(-5,7),35,95); p.morale=clamp(p.morale+rand(-4,5),35,95);
 if(Math.random()<.2 && p.age<28) p.ovr=clamp(p.ovr+(p.ovr<p.potential?rand(0,2):-1),40,99);
 if(p.contractYears<1 && Math.random()<.35) generateOffer();
 save();render();}
function playMatch(f){const c=club(),opp=state.clubs.find(x=>x.id===f.opponentId);const base=(c.reputation-opp.reputation)+(user().ovr-65);const chance=clamp(.5+base/180,.2,.8);const win=Math.random()<chance;const draw=!win&&Math.random()<.28;let gf=draw?rand(0,2):win?rand(1,4):rand(0,1);let ga=draw?gf:win?rand(0,Math.max(0,gf-1)):rand(1,4);if(gf===ga)draw=true;f.result=`${gf}–${ga}`;f.rating=(6.2+Math.random()*2.4).toFixed(1);f.date=`${state.year}-${String(state.month).padStart(2,'0')}-${String(state.day).padStart(2,'0')}`;c.gf+=gf;c.ga+=ga;opp.gf+=ga;opp.ga+=gf;if(gf>ga)c.wins++,c.points+=3;else if(gf===ga)c.draws++,c.points++,opp.draws++,opp.points++;else c.losses++;if(ga>gf)opp.wins++,opp.points+=3;else if(ga===gf){}else opp.losses++;const p=user();p.apps++;if(Math.random()<.55){p.goals+=rand(0,Math.min(2,gf));p.assists+=rand(0,Math.min(1,gf));}p.form=clamp(p.form+(win?rand(3,8):rand(-4,2)),1,99);state.news.unshift(`${p.name} played ${f.result} against ${opp.name}.`);f.opponent=opp.name;}
function generateOffer(){const candidates=state.clubs.filter(c=>c.id!==club().id);const c=pick(candidates);const p=user();state.offers.push({clubId:c.id,clubName:c.name,wage:Math.max(p.wage+rand(3000,18000),p.wage),years:rand(2,5),fee:Math.round(p.value*rand(85,125)/100),release:Math.round(p.value*1.8),role:p.ovr>75?'Starter':'Rotation'});state.news.unshift(`${c.name} has submitted a transfer offer for ${p.name}.`);}
function negotiate(){const p=user();const raise=Math.round(p.wage*(1.08+Math.random()*.18));const years=rand(2,5);p.wage=raise;p.contractYears=years;state.news.unshift(`${p.name} signs a ${years}-year extension for ${money(raise)}/week.`);save();render();}
function acceptOffer(i){const o=state.offers[i],p=user(),old=club(),next=state.clubs.find(c=>c.id===o.clubId);state.career.push({season:`${state.year}/${String(state.year+1).slice(2)}`,club:old.name,apps:p.apps,goals:p.goals});p.clubId=next.id;state.user.clubId=next.id;p.wage=o.wage;p.contractYears=o.years;p.morale=82;state.offers=[];state.news.unshift(`${p.name} transfers from ${old.name} to ${next.name}.`);save();render();}
function rejectOffer(i){state.news.unshift(`Transfer offer from ${state.offers[i].clubName} rejected.`);state.offers.splice(i,1);save();render();}
function finishSeason(){const p=user(),c=club();state.career.push({season:`${state.year}/${String(state.year+1).slice(2)}`,club:c.name,apps:p.apps,goals:p.goals});const pos=positionOf(c.id);if(pos<=2&&c.division>1){c.division--;state.news.unshift(`${c.name} is promoted to Division ${c.division}.`);}if(pos>=state.clubs.filter(x=>x.division===c.division).length-1&&c.division<2){c.division++;state.news.unshift(`${c.name} is relegated to Division ${c.division}.`);}state.clubs.forEach(x=>{x.points=0;x.wins=0;x.draws=0;x.losses=0;x.gf=0;x.ga=0});state.year++;state.fixtures=[];generateFixtures();state.players.forEach(x=>{x.age+=1;if(x.age>35)x.ovr=clamp(x.ovr-rand(1,4),35,99);else if(x.age<27)x.ovr=clamp(x.ovr+(x.ovr<x.potential?rand(0,2):rand(-1,1)),35,99);x.contractYears=Math.max(0,x.contractYears-1);if(x.contractYears===0&&x.id!=='user')x.contractYears=rand(1,4);});if(p.age>=38){state.news.unshift(`${p.name} retires from professional football.`);} }
function generateFixtures(){const divs=[1,2];divs.forEach(div=>{const teams=state.clubs.filter(c=>c.division===div);for(let r=0;r<2;r++)for(let i=0;i<teams.length;i++)for(let j=i+1;j<teams.length;j++){const home=r===0?teams[i]:teams[j],away=r===0?teams[j]:teams[i];state.fixtures.push({clubId:home.id,opponentId:away.id,opponent:away.name,home:true,result:null,date:null});state.fixtures.push({clubId:away.id,opponentId:home.id,opponent:home.name,home:false,result:null,date:null});}});}
if(!state.fixtures.length)generateFixtures();
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;save();render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions(b.dataset.action));document.querySelectorAll('[data-offer]').forEach(b=>b.onclick=()=>b.dataset.choice==='accept'?acceptOffer(+b.dataset.offer):rejectOffer(+b.dataset.offer));}
function actions(a){if(a==='advance')advance();if(a==='save'){save();alert('Career saved.')}if(a==='new'&&confirm('Start a new career? Current save will be replaced.')){localStorage.removeItem(KEY);state=null;state=seed();render()}if(a==='negotiate')negotiate();if(a==='request'){generateOffer();save();render();}}
render();